openapi: 3.0.3
info:
  title: Minha API
  description: Documentação automática baseada nas rotas do projeto
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Ponto de entrada da API
      description: Retorna uma mensagem de boas-vindas.
      responses:
        '200':
          description: Mensagem de boas-vindas
          content:
            text/plain:
              schema:
                type: string
  /create/app:
    post:
      summary: Cria um novo app
      description: Necessita validação de admin. Endpoint para criar um novo aplicativo.
      responses:
        '200':
          description: App criado com sucesso
        '401':
          description: Falha na validação do admin
  /delete/app:
    delete:
      summary: Remove um app existente
      description: Necessita usuário admin válido. Endpoint para deletar um app.
      responses:
        '200':
          description: App deletado com sucesso
        '401':
          description: Usuário admin não autorizado
  /auth/create:
    post:
      summary: Cria um usuário admin
      description: Endpoint para criar usuários administradores.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Usuário admin criado com sucesso
        '400':
          description: Dados inválidos
  /auth/login:
    post:
      summary: Login de usuário admin
      description: Endpoint para autenticar administradores.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciais inválidas
  /token:
    get:
      summary: Obter token admin
      description: Retorna um token de autenticação para usuários admin.
      responses:
        '200':
          description: Token retornado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /v1/auth/create:
    post:
      summary: Cria um usuário cliente
      description: Necessita app válido. Endpoint para criar usuários clientes.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Usuário cliente criado com sucesso
        '401':
          description: App inválido
  /v1/auth/login:
    post:
      summary: Login de usuário cliente
      description: Necessita app válido. Endpoint para autenticar usuários clientes.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciais inválidas
  /v1/token:
    get:
      summary: Obter token cliente
      description: Retorna um token de autenticação para usuários clientes.
      responses:
        '200':
          description: Token retornado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
